export type Language = "en" | "vi";

export const defaultGoalKm = 18;

export const stravaScopes = [
  "read",
  "activity:read_all",
  "profile:read_all",
] as const;

export const languageCopy = {
  en: {
    brandName: "love running",
    brandTagline: "Minimal couple dashboard",
    languageSwitch: "Switch language",
    dashboardNav: "Dashboard",
    demoNav: "Demo",
    heroKicker: "Couple heart goal",
    heroTitle: "Turn every kilometer into one shared heart.",
    heroDescription:
      "Track both runners in one daily dashboard, combine your total distance, and complete the heart together.",
    moreDetails: "More details",
    nicknameKicker: "Couple names",
    nicknameTitle: "Set the names shown across your shared dashboard.",
    editNames: "Set names",
    yourNicknameLabel: "Your nickname",
    partnerNicknameLabel: "Partner nickname",
    saveNames: "Save names",
    namesSaved: "Names saved.",
    namesSaving: "Saving names...",
    closeModal: "Close",
    goalInputLabel: "Shared distance goal",
    editGoal: "Set goal",
    editGoalHint: "edit",
    totalGoalLabel: "Goal to complete the heart",
    totalRunLabel: "Distance already run",
    toCompleteLabel: "Distance left",
    saveGoal: "Save shared goal",
    goalSaved: "Shared goal saved.",
    goalSaving: "Saving goal...",
    pairingKicker: "Pair together",
    pairingTitle: "Generate a code for your partner or join with their code.",
    generateCode: "Generate pairing code",
    joinCode: "Join with code",
    pairingInputPlaceholder: "Enter code",
    pairingConnected: "Paired successfully",
    pairingWaiting: "Waiting for partner to join",
    pairingCodeLabel: "Pairing code",
    demoKicker: "Strava success demo",
    demoTitle: "Preview the heart, custom runner stats, and generated audio before going live.",
    demoDescription:
      "Use this playground to simulate a successful Strava connection, edit each runner's values, and hear how the generated couple song responds.",
    demoDistanceLabel: "Distance",
    demoAudioKicker: "Generated audio",
    demoAudioTitle: "How the couple song would be generated",
    demoAudioDescription:
      "The demo song uses both runners' heart-rate patterns, maps them into tempo and note changes, and loops a soft synth line in the browser.",
    demoAudioFormula: "Generation logic",
    demoTempoLabel: "Generated tempo",
    demoMoodLabel: "Sound mood",
    demoAudioLocked: "Connect both demo runners",
    needMoreEffortLabel: "Need more effort",
    kmUnit: "km",
    youLabel: "You",
    partnerLabel: "Partner",
    connectYou: "Connect your Strava",
    connectPartner: "Connect partner Strava",
    setCredentials: "Set Strava app",
    clientIdLabel: "Client ID",
    clientSecretLabel: "Client secret",
    redirectUriLabel: "Redirect URI",
    saveCredentials: "Save Strava app",
    credentialsSaving: "Saving Strava app...",
    credentialsSaved: "Strava app saved.",
    stravaCredentialsTitle: "Save Strava app credentials",
    stravaCredentialsDescription: "Each runner can use a different Strava app. Save that runner's client ID, client secret, and redirect URI here before connecting.",
    disconnect: "Disconnect",
    connectedStatus: "Connected",
    disconnectedStatus: "Not connected",
    todayLabel: "Today",
    loading: "Loading live Strava dashboard...",
    refresh: "Refresh data",
    stepEstimateNote:
      "Steps are estimated from Strava cadence because Strava does not expose a direct steps total in the API.",
    liveError: "Could not load live Strava data.",
    heartRateLabel: "Heart rate",
    stepsLabel: "Steps",
    caloriesLabel: "Calories",
    runCountLabel: "Runs today",
    summaryKicker: "Daily sync",
    summaryTitle: "Combined Strava snapshot",
    summaryNote:
      "Live values come from today's Strava running activities for both people after authorization.",
    demoSetupNote:
      "This demo mirrors the dashboard layout, but lets you simulate successful connections and edit each runner's values before going live.",
    combinedHeartRateLabel: "Combined avg. heart rate",
    combinedStepsLabel: "Combined steps",
    combinedCaloriesLabel: "Combined calories",
    authKicker: "Strava setup",
    authTitle: "Authorize both runners on dashboard",
    authConnected: "Strava sent an authorization code to this dashboard and the backend stored it successfully.",
    authError: "Strava authorization was cancelled or failed. You can retry the connection from this dashboard.",
    authSteps: [
      "Create a Strava API app and set the Authorization Callback Domain to your dashboard domain only.",
      "Use a single redirect URI that ends exactly at /dashboard because your app keeps authorization on the dashboard screen.",
      "Store VITE_STRAVA_CLIENT_ID and VITE_STRAVA_REDIRECT_URI for the frontend authorize link, then exchange the code on your backend with STRAVA_CLIENT_SECRET.",
      "Request read, profile:read_all, and activity:read_all so you can fetch athlete profile, runs, heart rate streams, and activity details after consent.",
    ],
    songKicker: "Heartbeat song",
    songTitle: "Generate a couple song after the heart is complete",
    songReadyDescription:
      "The shared goal is complete. You can now unlock a generated song concept from both runners' heart-rate patterns.",
    songLockedDescription:
      "This unlocks when the total distance goal reaches 100 percent. The song can be generated from both heart-rate streams after that.",
    songButtonLocked: "Locked until complete",
    songButtonPlay: "Play generated song",
    songButtonPause: "Pause song",
  },
  vi: {
    brandName: "love running",
    brandTagline: "Bảng điều khiển tối giản cho cặp đôi",
    languageSwitch: "Chuyển ngôn ngữ",
    dashboardNav: "Dashboard",
    demoNav: "Demo",
    heroKicker: "Mục tiêu trái tim cặp đôi",
    heroTitle: "Biến từng kilomet thành một trái tim chung.",
    heroDescription:
      "Theo dõi hai người chạy trong một dashboard theo ngày, cộng tổng quãng đường và cùng hoàn thành trái tim.",
    moreDetails: "Xem thêm",
    nicknameKicker: "Tên hiển thị",
    nicknameTitle: "Đặt tên hiển thị cho hai người trên dashboard chung.",
    editNames: "Đặt tên",
    yourNicknameLabel: "Tên của bạn",
    partnerNicknameLabel: "Tên người kia",
    saveNames: "Lưu tên",
    namesSaved: "Đã lưu tên.",
    namesSaving: "Đang lưu tên...",
    closeModal: "Đóng",
    goalInputLabel: "Mục tiêu quãng đường chung",
    editGoal: "Đặt goal",
    editGoalHint: "chỉnh sửa",
    totalGoalLabel: "Goal để hoàn thành trái tim",
    totalRunLabel: "Quãng đường đã chạy",
    toCompleteLabel: "Quãng đường còn lại",
    saveGoal: "Lưu goal chung",
    goalSaved: "Đã lưu goal chung.",
    goalSaving: "Đang lưu goal...",
    pairingKicker: "Ghép đôi",
    pairingTitle: "Tạo mã cho người kia hoặc nhập mã để ghép đôi.",
    generateCode: "Tạo mã ghép đôi",
    joinCode: "Nhập mã để ghép",
    pairingInputPlaceholder: "Nhập mã",
    pairingConnected: "Đã ghép đôi thành công",
    pairingWaiting: "Đang chờ người kia nhập mã",
    pairingCodeLabel: "Mã ghép đôi",
    demoKicker: "Demo kết nối Strava",
    demoTitle: "Xem trước trái tim, chỉnh tay số liệu của từng người và nghe audio tạo ra trước khi chạy thật.",
    demoDescription:
      "Dùng playground này để giả lập kết nối Strava thành công, chỉnh từng chỉ số của mỗi người và nghe thử bài nhạc cặp đôi được tạo trong trình duyệt.",
    demoDistanceLabel: "Quãng đường",
    demoAudioKicker: "Audio tạo ra",
    demoAudioTitle: "Bài nhạc cặp đôi sẽ được tạo như thế nào",
    demoAudioDescription:
      "Bài nhạc demo dùng nhịp tim của cả hai, đổi thành tempo và cao độ, rồi phát một lớp synth mềm ngay trong trình duyệt.",
    demoAudioFormula: "Logic tạo nhạc",
    demoTempoLabel: "Tempo tạo ra",
    demoMoodLabel: "Màu âm thanh",
    demoAudioLocked: "Hãy bật kết nối cho cả hai",
    needMoreEffortLabel: "Cần thêm nỗ lực",
    kmUnit: "km",
    youLabel: "Bạn",
    partnerLabel: "Người kết đôi",
    connectYou: "Kết nối Strava của bạn",
    connectPartner: "Kết nối Strava người kia",
    setCredentials: "Lưu app Strava",
    clientIdLabel: "Client ID",
    clientSecretLabel: "Client secret",
    redirectUriLabel: "Redirect URI",
    saveCredentials: "Lưu app Strava",
    credentialsSaving: "Đang lưu app Strava...",
    credentialsSaved: "Đã lưu app Strava.",
    stravaCredentialsTitle: "Lưu thông tin app Strava",
    stravaCredentialsDescription: "Mỗi runner có thể dùng một Strava app khác nhau. Hãy lưu client ID, client secret và redirect URI của runner đó trước khi kết nối.",
    disconnect: "Ngắt kết nối",
    connectedStatus: "Đã kết nối",
    disconnectedStatus: "Chưa kết nối",
    todayLabel: "Hôm nay",
    loading: "Đang tải dashboard Strava thật...",
    refresh: "Làm mới dữ liệu",
    stepEstimateNote:
      "Số bước được ước tính từ cadence của Strava vì API Strava không trả trực tiếp tổng steps.",
    liveError: "Không thể tải dữ liệu Strava thật.",
    heartRateLabel: "Nhịp tim",
    stepsLabel: "Số bước",
    caloriesLabel: "Calories",
    runCountLabel: "Số buổi chạy hôm nay",
    summaryKicker: "Tổng quan trong ngày",
    summaryTitle: "Ảnh chụp dữ liệu Strava của cả hai",
    summaryNote:
      "Các giá trị bên dưới được lấy từ hoạt động chạy trong ngày của cả hai trên Strava sau khi cấp quyền.",
    demoSetupNote:
      "Bản demo này dùng cùng bố cục với dashboard, nhưng cho bạn giả lập kết nối thành công và chỉnh tay số liệu của từng người trước khi chạy thật.",
    combinedHeartRateLabel: "Nhịp tim TB kết hợp",
    combinedStepsLabel: "Tổng số bước",
    combinedCaloriesLabel: "Tổng calories",
    authKicker: "Thiết lập Strava",
    authTitle: "Authorize cả hai ngay trên dashboard",
    authConnected: "Strava đã trả authorization code về dashboard này và backend đã lưu token thành công.",
    authError: "Việc cấp quyền Strava đã bị huỷ hoặc lỗi. Bạn có thể thử kết nối lại ngay trên dashboard này.",
    authSteps: [
      "Tạo một app Strava API và đặt Authorization Callback Domain đúng với domain dashboard của bạn.",
      "Dùng duy nhất redirect URI kết thúc chính xác ở /dashboard vì ứng dụng giữ luồng cấp quyền ngay trên màn hình dashboard.",
      "Lưu VITE_STRAVA_CLIENT_ID và VITE_STRAVA_REDIRECT_URI cho link authorize phía frontend, sau đó đổi code ở backend bằng STRAVA_CLIENT_SECRET.",
      "Xin quyền read, profile:read_all và activity:read_all để lấy hồ sơ athlete, buổi chạy, nhịp tim và chi tiết activity sau khi người dùng đồng ý.",
    ],
    songKicker: "Bài hát nhịp tim",
    songTitle: "Tạo bài hát cặp đôi sau khi hoàn thành trái tim",
    songReadyDescription:
      "Mục tiêu chung đã hoàn thành. Bây giờ bạn có thể mở khoá ý tưởng bài hát được tạo từ nhịp tim của cả hai.",
    songLockedDescription:
      "Phần này sẽ mở khi goal quãng đường đạt 100 phần trăm. Sau đó có thể tạo bài hát từ dữ liệu nhịp tim của cả hai.",
    songButtonLocked: "Khoá đến khi hoàn thành",
    songButtonPlay: "Phát bài hát tạo sẵn",
    songButtonPause: "Tạm dừng bài hát",
  },
} as const;

export type Copy = (typeof languageCopy)[Language];
